post_later/urls.py
from django.urls import path  # noqa: F401

from . import views

app_name = "post_later"


urlpatterns = [
    path("socialaccounts/", view=views.AccountListView.as_view(), name="account_list"),
    path(
        "socialaccounts/create/",
        view=views.AccountCreateView.as_view(),
        name="account_create",
    ),
    path(
        "socialaccounts/<uuid:id>/",
        view=views.AccountDetailView.as_view(),
        name="account_detail",
    ),
    path(
        "socialaccounts/<uuid:id>/delete/",
        view=views.AccountDeleteView.as_view(),
        name="account_delete",
    ),
    path(
        "mastodon/add_account/",
        view=views.MastodonAccountAddView.as_view(),
        name="mastodon_add_account",
    ),
    path(
        "mastodon/handle_auth/<uuid:id>/",
        view=views.HandleMastodonAuthView.as_view(),
        name="mastodon_handle_auth",
    ),
    path(
        "mastodon/accounts/<uuid:id>/authorize/",
        view=views.MastodonLoginView.as_view(),
        name="mastodon_account_login",
    ),
]

post_later/models/abstract.py
from __future__ import annotations

import uuid
from datetime import datetime

from django.conf import settings
from django.core.files import File
from django.db import models
from django.utils.translation import gettext_lazy as _
from rules.contrib.models import RulesModel

from ..rules import is_owner, is_valid_user


class UUIDModel(models.Model):
    """
    A base model that uses a UUID for the primary key.

    Attributes:
        id (uuid): Primary key for the model.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class OwnedModel(UUIDModel, RulesModel):
    """
    An abstract model class that implements the basic ownership model
    and rules meta permission pattern.

    Attributes:
        id (uuid): Primary key for the model.
        user (AUTH_USER_MODEL): Foreign key to the associated instance of the project's `AUTH_USER_MODEL`.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        help_text=_("The user object that owns this instance."),
    )

    class Meta:
        abstract = True
        rules_permissions = {
            "add": is_valid_user,
            "read": is_owner,
            "edit": is_owner,
            "delete": is_owner,
            "list": is_valid_user,
        }


class RemoteUserAuthModel(models.Model):
    """
    Abstract model that enables a consistent API for remote accounts.
    Any connecting auth model intended to be used with `post_later.models.social_accounts.Account`
    must be a subclass of this model.

    Attributes:
        allows_remote_queueing (bool): Does this service support sending posts to be scheduled on the remote server?
    """

    allows_remote_queuing: bool

    def get_avatar_url(self) -> str | None:
        """
        Fetch the avatar url we are using if it exists.
        """
        raise NotImplementedError(
            self.__class__.__name__ + "get_avatar_url"
        )  # pragma: nocover

    def get_username(self) -> str | None:
        """
        Get the username of the account if already retrieved.
        """
        raise NotImplementedError(
            self.__class__.__name__ + "get_username"
        )  # pragma: nocover

    def get_remote_url(self) -> str | None:
        """
        Get the profile URL on the social service.
        """
        raise NotImplementedError(
            self.__class__.__name__ + "get_remote_url"
        )  # pragma: nocover

    def upload_media(self, media_object: File) -> str | None:
        """
        Upload a given media file to the remote server and return the media id.
        """
        raise NotImplementedError(
            self.__class__.__name__ + "upload_media"
        )  # pragma: nocover

    def send_post(
        self,
        content: str,
        media_ids: list[str] = [],
        in_response_to_id: str | None = None,
        schedule_time: datetime | None = None,
    ) -> tuple[str, str | None]:
        """
        Sends the post to the remote server and either returns the remote id as a string
        or raises an exception on error.

        Returns a tuple of the remote id and remote url of the post. The url will be None if a scheduled post.
        """
        raise NotImplementedError(
            self.__class__.__name__ + "send_post"
        )  # pragma: nocover

    def username_search(self, name_fragment: str) -> list[str]:
        """
        Given a fragment of a username, attempt to do a search on the remote server for use in
        tagging other accounts in a scheduled post.
        """
        raise NotImplementedError(
            self.__class__.__name__ + "username_search"
        )  # pragma: nocover

    @property
    def is_ready_post(self) -> bool:
        """
        Validates if the user auth object is fully authenticated
        and ready to post.
        """

        raise NotImplementedError(
            self.__class__.__name__ + "is_ready_post"
        )  # pragma: nocover

    class Meta:
        abstract = True

post_later/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from .models.social_accounts import Account


class LinkMastodonAccountForm(forms.Form):
    """
    Custom form that we use to collect the remote instance domain.
    """

    instance_url = forms.fields.URLField(
        label=_("Server URL"),
        help_text=_("Include the full domain, e.g. https://mastodon.social"),
    )


class AccountCreateForm(forms.Form):
    """
    Custom form that we use to start account linking process.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        account_choices = []
        for allowed_account_type in settings.ENABLED_ACCOUNT_TYPES:
            try:
                enum_value = getattr(Account.AccountType, allowed_account_type)
                account_choices.append((enum_value.value, enum_value.label))
            except KeyError:  # pragma: nocover
                pass
        self.fields["account_type"].choices = account_choices  # type: ignore

    account_type = forms.ChoiceField(
        choices=[],
        help_text=_("Type of account you wish to link."),
        label=_("Account Type"),
    )

post_later/views/mastodon.py
from __future__ import annotations

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from mastodon import Mastodon, MastodonError
from rules.contrib.views import PermissionRequiredMixin

from ..forms import LinkMastodonAccountForm
from ..models import Account, MastodonAvatar, MastodonInstanceClient, MastodonUserAuth


class MastodonAccountAddView(LoginRequiredMixin, FormView):
    """
    A view that enables users to connect another Mastodon
    account to their profile. It should take the intial values of
    the api_base_url and then get_or_create a client and start the
    OAuth Flow.

    It will attempt to create a new app on the remote instance if needed
    and store the resulting client_id and client_secret returned.

    If successful, redirects to remote instance to start OAuth
    approval by user.
    """

    form_class = LinkMastodonAccountForm
    template_name = "post_later/mastodon/link_account.html"

    def form_valid(self, form):
        """
        Uses the instance URL to create server client if needed, then proceeds to
        authorization.
        """

        url = form.cleaned_data["instance_url"]
        with transaction.atomic():
            client, created = MastodonInstanceClient.objects.get_or_create(
                api_base_url=url
            )
            new_account = Account.objects.create(user=self.request.user)  # type: ignore
            userauth = MastodonUserAuth.objects.create(
                instance_client=client,
                user=self.request.user,  # type: ignore
                social_account=new_account,
            )
            redirect_url = reverse_lazy(
                "post_later:mastodon_handle_auth", kwargs={"id": userauth.id}
            )
            if created or not client.ready:
                # This one isn't actually registered with the instance.
                client_key, client_secret = Mastodon.create_app(
                    client_name="Post Later",
                    api_base_url=url,
                    redirect_uris=redirect_url,
                )
                client.client_id = client_key
                client.client_secret = client_secret
                client.save()
        mclient = Mastodon(
            api_base_url=url,
            client_id=client.client_id,
            client_secret=client.client_secret,
        )
        return HttpResponseRedirect(
            mclient.auth_request_url(redirect_uris=redirect_url)
        )


class HandleMastodonAuthView(
    LoginRequiredMixin, PermissionRequiredMixin, SingleObjectMixin, TemplateView
):
    """
    Given the response from a Mastodon instance set the oauth key, and redirect to
    `MastodonLoginView` to finish authenticating the user.

    Displays an error message if no oauth key is returned.
    """

    model = MastodonUserAuth
    pk_url_kwarg = "id"
    select_related = ["instance_client", "mastodonavatar"]
    code: str | None = None
    context_object_name = "auth_object"
    template_name = "post_later/mastodon/mastodon_error.html"
    mastodon_error_text = None
    permission_required = "post_later.edit_mastodonuserauth"

    def dispatch(self, request, *args, **kwargs):
        """
        If code is supplied, pull it out into a property.
        """

        self.code = request.GET.get("code", None)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.code is not None:
            self.object.user_oauth_key = self.code
            self.object.user_auth_token = None
            self.object.save()
            return HttpResponseRedirect(
                reverse_lazy(
                    "post_later:mastodon_account_login", kwargs={"id": self.object.id}
                )
            )
        else:
            self.mastodon_error_text = _(
                "Your mastodon server did not return an authorization code."
            )
        return super().get(request, *args, **kwargs)


class MastodonLoginView(
    LoginRequiredMixin, PermissionRequiredMixin, SingleObjectMixin, TemplateView
):
    """
    Requests an auth token from the Mastodon instance and saves it to `MastodonUserAuth`.
    Then redirects to associated `AccountDetailView`. Otherwise, displays the error message
    received from Mastodon.
    """

    model = MastodonUserAuth
    pk_url_kwarg = "id"
    select_related = ["instance_client", "mastodonavatar"]
    auth_token = None
    template_name = "post_later/mastodon/mastodon_error.html"
    mastodon_error_text = None
    context_object_name = "userauth"
    permission_required = "post_later.edit_mastodonuserauth"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        mclient = Mastodon(
            client_id=self.object.instance_client.client_id,
            client_secret=self.object.instance_client.client_secret,
            api_base_url=self.object.instance_client.api_base_url,
        )
        try:
            access_token = mclient.log_in(code=self.object.user_oauth_key)
            self.object.user_auth_token = access_token
            mclient = Mastodon(
                access_token=self.object.user_auth_token,
                api_base_url=self.object.instance_client.api_base_url,
            )
            user_info = mclient.me()
            self.object.account_username = user_info["acct"]
            self.object.account_url = user_info["url"]
            self.object.save()
            avatar, created = MastodonAvatar.objects.get_or_create(
                user_account=self.object
            )
            if created or avatar.source_url != user_info["avatar_static"]:
                avatar.source_url = user_info["avatar_static"]
                avatar.cache_stale = True
                avatar.save()
            return HttpResponseRedirect(
                reverse_lazy(
                    "post_later:account_detail",
                    kwargs={"id": self.object.social_account.id},
                )
            )
        except MastodonError as eme:
            self.mastodon_error_text = f"Mastodon Error: {eme}"
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Add mastodon error message to context data if login fails.
        """

        context = super().get_context_data(**kwargs)
        context["mastodon_error"] = self.mastodon_error_text
        return context

post_later/views/social_accounts.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, FormView, ListView
from django.views.generic.edit import DeleteView
from rules.contrib.views import PermissionRequiredMixin

from ..forms import AccountCreateForm
from ..models import Account


class AccountListView(LoginRequiredMixin, ListView):
    """
    Displays the list of accounts associated with the account.
    Can also be filtered additionally with GET params such as
    `type=mastodon`.
    """

    model = Account
    pk_url_kwarg = "id"
    template_name = "post_later/account_list.html"
    select_related = ["stats"]
    paginate_by = 25
    context_object_name = "accounts"
    ordering = ["created"]

    def get_queryset(self):
        """
        Return a queryset filtered to the current user and by type if
        in query string.
        """

        get_params = self.request.GET.copy()
        type_filter = get_params.get("account_type", None)
        queryset = self.model.objects.filter(user=self.request.user)  # type: ignore
        if type_filter:
            queryset = queryset.filter(account_type=type_filter)
        return queryset


class AccountCreateView(LoginRequiredMixin, FormView):
    """
    Initial view to use when creating an account link.
    """

    form_class = AccountCreateForm
    template_name = "post_later/account_create.html"

    def form_valid(self, form):
        """
        Use the type to direct the next step accordingly.
        """
        type_to_use = form.cleaned_data["account_type"]
        return HttpResponseRedirect(
            reverse_lazy(f"post_later:{type_to_use}_add_account")
        )


class AccountDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    """
    View that shows the detail of a created account, including status, statistics, and associated
    data from the linked auth object associated with the service.
    """

    model = Account
    pk_url_kwarg = "id"
    context_object_name = "account"
    select_related = ["stats"]
    template_name = "post_later/account_detail.html"
    permission_required = "post_later.read_account"


class AccountDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """
    View for deleting an existing account.
    """

    model = Account
    pk_url_kwarg = "id"
    context_object_name = "account"
    permission_required = "post_later.delete_account"
    template_name = "post_later/account_delete.html"
    object: Account

    def get_success_url(self):
        messages.success(self.request, _("Successfully deleted account."))  # type: ignore
        return reverse_lazy("post_later:account_list")

post_later/templates/post_later/account_create.html
{% extends "post_later/app_base.html" %}
{% load i18n crispy_forms_tags %}
{% block extratitle %}{% translate "Add Account" %} - {% endblock %}
{% block content %}
<h1>{% translate "Add new account" %}</h1>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <a href="{% url 'post_later:account_list' %}">{% translate "Go back to account list" %}</a> <button type="submit">{% translate "Add account" %}</button>
</form>
{% endblock %}

post_later/templates/post_later/account_delete.html
{% extends "post_later/app_base.html" %}
{% load i18n %}
{% block extratitle %}{% translate "Delete account:" %} {{ account.username }} - {% endblock %}
{% block content %}
<h1>{% translate "Are you sure you want to delete this account?" %}</h1>
<p>{% translate "If you proceed this will also delete any pending scheduled posts, threads, or media associated with this account." %}</p>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <a href="{% url 'post_later:account_detail' id=account.id %}">{% translate "Back to account detail" %}</a> <button type="submit">{% translate "Delete" %}</button>
</form>
{% endblock %}

post_later/templates/post_later/account_detail.html
{% extends "post_later/app_base.html" %}
{% load i18n %}
{% block extratitle %}{% translate "Account detail:" %} {{ account.username }} - {% endblock %}
{% block content %}
<h1>{% translate "Account detail" %}</h1>
<figure>
  {% if account.avatar_url %}<img src={{ account.avatar_url }} height=50, width=50 alt="account avatar" />{% endif %}
  <dl>
    <dt>{% translate "Account Type" %}</dt>
    <dd>{{ account.get_account_type_display }}</dd>
    <dt>{% translate "Account Status" %}</dt>
    <dd>{{ account.get_account_status_display }}</dd>
    <dt>{% translate "Account Username" %}</dt>
    <dd>{{ account.username }}</dd>
    <dt>{% translate "Account URL" %}</dt>
    <dd>{% if account.remote_url %}<a href="{{ account.remote_url }}" target="_blank">{{ account.remote_url }}</a>{% else %}{% translate "Pending" %}{% endif %}</dd>
  </dl>
  <h2>{% translate "Statistics" %}</h2>
  <table>
    <thead>
      <tr>
        <th scope='col'>{% translate "Total posts scheduled" %}</th>
        <th scope='col'>{% translate "Total posts sent" %}</th>
        <th scope='col'>{% translate "Total threads scheduled" %}</th>
        <th scope='col'>{% translate "Total threads sent" %}</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ account.stats.num_posts_scheduled }}</td>
        <td>{{ account.stats.num_posts_sent }}</td>
        <td>{{ account.stats.num_threads_scheduled }}</td>
        <td>{{ account.stats.num_threads_sent }}</td>
      </tr>
    </tbody>
  </table>
  <a href="{% url 'post_later:account_list' %}">{% translate "Back to account list" %}</a> {% if account.account_status == "pending" %}{# Add a link to a view that will allow us to resume the authentication process. #}{% endif %}<a href="{% url 'post_later:account_delete' id=account.id %}">{% translate "Delete account" %}</a>
</figure>
{% endblock %}

post_later/templates/post_later/account_list.html
{% extends "post_later/app_base.html" %}
{% load i18n %}
{% block extratitle %}{% translate "Account List" %} - {% endblock %}
{% block content %}
<h1>{% translate "Your accounts" %}</h1>
<table>
  <caption>{% translate "Showing" %} {{ page_obj|length }} {% translate "of" %} {{ page_obj.paginator.object_list.count }}</caption>
  <thead>
    <tr>
      <th scope="col">{% translate "Account Type" %}</th>
      <th scope="col">{% translate "Account User" %}</th>
      <th scope="col">{% translate "Account Status" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for account in accounts %}
    <tr>
      <td>{{ account.get_account_type_display }}</td>
      <td>{% if account.avatar_url %}<img src={{ account.avatar_url }} height=20 width=20 alt="User avatar" />&nbsp;{% endif %}<a href="{{ account.get_absolute_url }}">{% if account.username %}{{ account.username }}{% else %}{% translate "Awaiting data from remote service" %}{% endif %}</a></td>
      <td>{{ account.get_account_status_display }}</td>
    </tr>
    {% empty %}
    <tr>
      <td></td>
      <td>{% translate "No accounts found!" %}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<p><a href="{% url 'post_later:account_create' %}">{% translate "Link new account" %}</a></p>
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a href="?page=1">&laquo; {% trans "First" %}</a></li>
    <li><a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a></li>
    {% endif %}
    <li aria-current="page"><a href="#">{{ page_obj.number }}</a></li>
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a></li>
    <li><a href="?page={{ page_obj.paginator.num_pages }}">{% translate "Last" %}</a></li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}

post_later/templates/post_later/app_base.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% block extratitle %}{% endblock %}{% translate "Post Later" %}{% endblock %}